spring.application.name=StudentManagement

spring.datasource.url=jdbc:mysql://localhost:3308/StudentManagement2
spring.datasource.username=root
spring.datasource.password=Mosanachio1148
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:/mapper/*.xml
mybatis.mapper-locations=classpath:/mapper/*.xml


# ???????Spring Boot ?????? /static/ ?????????
#spring.web.resources.static-locations=classpath:/static/

# ????? ? index.html ?????
# spring.mvc.view.prefix=/
# spring.mvc.view.suffix=.html
